# Generated by Django 6.1 on 2026-09-10 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ficha_medica', serialize=False, to='veterinaria.mascota')),
                ('codigo_chip', models.CharField(max_length=50, unique=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='dueno_nombre',
            field=models.CharField(max_length=100, verbose_name='Dueño'),
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='veterinaria.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('indicaciones_uso', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_receta', to='veterinaria.citamedica')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_receta', to='veterinaria.insumo')),
            ],
        ),
        migrations.AddField(
            model_name='citamedica',
            name='insumos_recetados',
            field=models.ManyToManyField(related_name='citas_asociadas', through='veterinaria.DetalleReceta', to='veterinaria.insumo'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='veterinaria.historialmedico')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegiatura', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_veterinario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='citamedica',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='veterinaria.perfilveterinario'),
        ),
    ]
