# Generated by Django 6.1 on 2026-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=100)),
                ('paciente_telefono', models.CharField(max_length=9)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo_consulta', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
