# Generated by Django 6.1 on 2026-09-10 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_fichamedica_alter_mascota_dueno_nombre_citamedica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='veterinario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='veterinaria.perfilveterinario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_receta', to='veterinaria.insumo'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='mascota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='veterinaria.mascota'),
        ),
        migrations.AlterField(
            model_name='perfilveterinario',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_veterinario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
